import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, BookOpen, BriefcaseBusiness, ChevronRight, Download, GitFork, Mail, Menu, Network, X } from 'lucide-react'
import { nav, projects, skills } from './data'

const fadeUp = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: .15 }, transition: { duration: .55 } }

function Nav() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const scroll = () => setScrolled(scrollY > 20); addEventListener('scroll', scroll); return () => removeEventListener('scroll', scroll) }, [])
  return <header className={`nav ${scrolled ? 'nav-scrolled' : ''}`}><a href="#home" className="mark" aria-label="Cade Schiano home">CS<span>.</span></a><nav className={open ? 'open' : ''}>{nav.map(item => <a onClick={() => setOpen(false)} key={item} href={`#${item.toLowerCase()}`}>{item}</a>)}<a href="#contact" className="nav-cta">Let's talk <ArrowUpRight size={14}/></a></nav><button className="menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button></header>
}

function ProjectVisual({ accent, index }: { accent: string, index: number }) {
  if (index === 0) return <div className={`project-visual ${accent}`}><div className="map-grid"/><div className="map-route"><i/><i/><i/><i/></div><div className="mini-card card-a"><small>TODAY</small><b>12 visits</b></div><div className="mini-card card-b"><span>◉</span> Cleveland, OH</div></div>
  if (index === 1) return <div className={`project-visual ${accent}`}><div className="dashboard"><div className="dash-side"><i/><i/><i/><i/></div><div className="dash-body"><div className="dash-top"><b>Activity overview</b><span>This week</span></div><div className="stat-row"><b>24h</b><b>+18%</b><b>8</b></div><div className="bars">{[44,68,42,82,60,94,55,70].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></div></div>
  if (index === 2) return <div className={`project-visual ${accent}`}><div className="phone"><div className="phone-head"><span>My lists</span><b>+</b></div>{['Weekend groceries', 'Mom’s birthday', 'Apartment essentials'].map((x,i)=><div className="list-row" key={x}><i className={i===0?'checked':''}/><span>{x}</span><small>{[8,3,12][i]}</small></div>)}</div></div>
  return <div className={`project-visual ${accent}`}><div className="bracket"><span>QUARTERFINALS</span><i/><i/><i/><i/><span>SEMIFINALS</span><i/><i/><span>FINALS</span><i/></div><div className="soon">Coming<br/><em>soon</em></div></div>
}

function App() {
  return <><Nav/><main>
    <section className="hero" id="home"><div className="hero-glow one"/><div className="hero-glow two"/><div className="orb orb-one"/><div className="orb orb-two"/><motion.div {...fadeUp} className="eyebrow"><span/> Available for internships</motion.div><motion.h1 {...fadeUp} transition={{duration:.65, delay:.08}}>I build digital<br/><em>experiences</em> with intent.</motion.h1><motion.p {...fadeUp} transition={{delay:.16}}>I’m Cade Schiano — a software engineering student turning thoughtful ideas into polished web, mobile, and backend products.</motion.p><motion.div {...fadeUp} transition={{delay:.22}} className="hero-actions"><a className="button primary" href="#projects">Explore my work <ArrowDownRight size={18}/></a><a className="button quiet" href="./resume-cade-schiano.pdf" download>Download resume <Download size={17}/></a></motion.div><div className="hero-foot"><span>Scroll to explore</span><div/><span>BGSU · Software Engineering</span></div></section>

    <section className="intro section" id="about"><motion.div {...fadeUp} className="section-label">01 — A little about me</motion.div><motion.div {...fadeUp} className="intro-grid"><h2>Curious by nature.<br/>Precise by practice.</h2><div><p className="large-copy">I’m a software engineering student at Bowling Green State University with a growing focus on full-stack systems and intuitive product experiences.</p><p>I like the moment when a difficult technical problem clicks into place — especially when that solution makes someone’s day a little easier. From APIs to mobile interfaces, I’m always looking for the connective tissue between people and technology.</p><a className="text-link" href="#experience">My background <ArrowUpRight size={16}/></a></div></motion.div><div className="facts"><div><span>Currently</span><b>Seeking a software<br/>engineering internship</b></div><div><span>Learning</span><b>Architecture, cloud,<br/>and better systems</b></div><div><span>Outside code</span><b>Rocket League esports<br/>team captain</b></div></div></section>

    <section className="projects section" id="projects"><motion.div {...fadeUp} className="project-heading"><div><div className="section-label">02 — Selected work</div><h2>Things I’ve<br/><em>brought to life.</em></h2></div><a className="text-link" href="https://github.com/CadeSchiano" target="_blank" rel="noreferrer">View GitHub <ArrowUpRight size={16}/></a></motion.div><div className="project-grid">{projects.map((project, index) => <motion.article {...fadeUp} transition={{duration:.45, delay:index*.06}} className={`project-card ${project.accent}`} key={project.title}><ProjectVisual accent={project.accent} index={index}/><div className="project-info"><div className="project-meta"><span>{project.kind}</span>{project.status && <span className="status">{project.status}</span>}</div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.stack.map(x=><span key={x}>{x}</span>)}</div><a href="https://github.com/CadeSchiano" target="_blank" rel="noreferrer" className="round-link" aria-label={`View ${project.title} on GitHub`}><ArrowUpRight size={19}/></a></div></motion.article>)}</div></section>

    <section className="skills section" id="skills"><motion.div {...fadeUp} className="skills-header"><div className="section-label">03 — Toolbox</div><h2>Solid fundamentals.<br/><em>Always expanding.</em></h2></motion.div><div className="skill-grid">{skills.map(([title, values])=><motion.div {...fadeUp} className="skill-column" key={title as string}><h3>{title}</h3><div>{(values as string[]).map((x,i)=><span key={x}><small>0{i+1}</small>{x}</span>)}</div></motion.div>)}</div></section>

    <section className="experience section" id="experience"><motion.div {...fadeUp} className="section-label">04 — Experience & education</motion.div><motion.div {...fadeUp} className="timeline"><article><div className="time-icon"><BookOpen size={20}/></div><div><span className="date">2023 — Present</span><h3>B.S. Software Engineering</h3><p>Bowling Green State University</p><p className="muted">Building a strong foundation in software architecture, database systems, security, and web applications.</p></div></article><article><div className="time-icon"><BriefcaseBusiness size={20}/></div><div><span className="date">Leadership</span><h3>Rocket League Team Captain</h3><p>Bowling Green State University Esports</p><p className="muted">Leading team strategy, creating a positive competitive environment, and developing clear communication under pressure.</p></div></article></motion.div></section>

    <section className="contact" id="contact"><div className="contact-glow"/><motion.div {...fadeUp}><div className="section-label">05 — Get in touch</div><h2>Let’s make something<br/><em>worth using.</em></h2><p>I’m currently looking for opportunities to learn, contribute, and build with great teams.</p><a href="mailto:cadeschiano8@yahoo.com" className="contact-mail">cadeschiano8@yahoo.com <ArrowUpRight/></a><div className="socials"><a href="https://github.com/CadeSchiano" target="_blank" rel="noreferrer" aria-label="GitHub"><GitFork size={19}/></a><a href="https://www.linkedin.com/in/cade-schiano" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Network size={19}/></a><a href="mailto:cadeschiano8@yahoo.com" aria-label="Email"><Mail size={19}/></a></div></motion.div></section>
  </main><footer><a className="mark" href="#home">CS<span>.</span></a><span>Designed & built by Cade Schiano</span><span>© {new Date().getFullYear()}</span></footer></>
}
export default App
