import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Braces, BrainCircuit, ChartNoAxesCombined, Download, ExternalLink, FileText, GitFork, Mail, Menu, Network, ShieldCheck, X } from 'lucide-react'
import { nav, projects, skillGroups, type Project } from './data'

const resume = `${import.meta.env.BASE_URL}resume-cade-schiano.pdf`
const github = 'https://github.com/CadeSchiano'
const linkedin = 'https://www.linkedin.com/in/cade-schiano-716645385'
const email = 'cadeschiano8@yahoo.com'
const reveal = { initial: { opacity: 0, y: 16 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.12 }, transition: { duration: 0.45 } }

function Nav() {
  const [open, setOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <header className={`nav ${scrolled ? 'nav-scrolled' : ''}`}><a className="mark" href="#home" aria-label="Cade Schiano home">CS<span>.</span></a><nav id="site-navigation" className={open ? 'open' : ''} aria-label="Primary navigation">{nav.map(item => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setOpen(false)}>{item}</a>)}<a href={resume} download onClick={() => setOpen(false)} className="nav-resume"><Download size={14}/> Résumé</a></nav><button className="menu" type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="site-navigation" aria-label={open ? 'Close navigation' : 'Open navigation'}>{open ? <X/> : <Menu/>}</button></header>
}

function ProjectMark({ project }: { project: Project }) {
  const Icon = project.tone === 'green' ? Braces : project.tone === 'blue' ? ShieldCheck : ChartNoAxesCombined
  return <div className={`project-mark ${project.tone}`} aria-hidden="true"><Icon strokeWidth={1.35}/><span>{project.category}</span><div className="mark-lines"><i/><i/><i/></div></div>
}

function ProjectCard({ project, index }: { project: Project, index: number }) {
  return <motion.article {...reveal} transition={{ duration: .45, delay: index * .05 }} className={`project-card project-${project.tone}`}><ProjectMark project={project}/><div className="project-content"><p className="project-category">{project.category}</p><h3>{project.name}</h3><p className="project-summary">{project.summary}</p><p className="project-built"><strong>What I built:</strong> {project.built}</p><div className="tags" aria-label={`${project.name} technologies`}>{project.stack.map(item => <span key={item}>{item}</span>)}</div><div className="project-actions"><a className="button compact subtle" href={project.source} target="_blank" rel="noreferrer">Source <GitFork size={15}/></a>{project.live && <a className="button compact card-live" href={project.live} target="_blank" rel="noreferrer">Live demo <ExternalLink size={15}/></a>}</div></div></motion.article>
}

function App() {
  return <><Nav/><main>
    <section className="hero" id="home"><div className="hero-grid" aria-hidden="true"/><div className="hero-orbit orbit-a" aria-hidden="true"/><div className="hero-orbit orbit-b" aria-hidden="true"/><motion.p {...reveal} className="eyebrow"><span/> Open to internships & early-career opportunities</motion.p><motion.h1 {...reveal} transition={{ duration: .55, delay: .05 }}>Cade Schiano<br/><em>Computer Science student</em><br/>& software developer.</motion.h1><motion.p {...reveal} transition={{ delay: .12 }} className="hero-copy">I build full-stack applications, backend APIs, and data-driven tools - with an emphasis on clear workflows, maintainable systems, and thoughtful product decisions.</motion.p><motion.div {...reveal} transition={{ delay: .18 }} className="hero-actions"><a className="button primary" href="#projects">View featured work <ArrowDownRight size={18}/></a><a className="button quiet" href={github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={17}/></a><a className="button quiet" href={resume} download>Résumé <Download size={16}/></a></motion.div><div className="hero-context"><span>BOWLING GREEN STATE UNIVERSITY</span><i/><span>COMPUTER SCIENCE · 2027</span></div></section>
    <section className="about section" id="about"><motion.div {...reveal} className="section-label">01 / About</motion.div><div className="about-grid"><motion.h2 {...reveal}>Building useful systems<br/>from <em>real constraints.</em></motion.h2><motion.div {...reveal}><p className="lead">I’m a Computer Science student at Bowling Green State University, graduating in 2027.</p><p>I’m most interested in product-oriented engineering: shaping a practical workflow, designing the data and API boundaries behind it, and carrying it through to a responsive interface. My current work spans full-stack applications, backend services, and machine learning pipelines.</p><a className="text-link" href="#education">Education & leadership <ArrowDownRight size={16}/></a></motion.div></div></section>
    <section className="projects section" id="projects"><motion.div {...reveal} className="section-heading"><div><p className="section-label">02 / Featured projects</p><h2>Work worth<br/><em>opening up.</em></h2></div><p>Three projects that best represent the systems I’m building now.</p></motion.div><div className="project-grid">{projects.map((project, index) => <ProjectCard project={project} index={index} key={project.name}/>)}</div><p className="screenshot-note"><FileText size={15}/> Product screenshots are being prepared from the current builds. Source and live links above lead to the real projects.</p></section>
    <section className="skills section" id="skills"><motion.div {...reveal} className="section-heading skills-heading"><div><p className="section-label">03 / Technical toolkit</p><h2>Tools I can<br/><em>defend in a room.</em></h2></div><p>Focused on technologies I use across current projects - not a long inventory of everything I have tried.</p></motion.div><div className="skill-grid">{skillGroups.map(([title, values]) => <motion.section {...reveal} className="skill-group" key={title as string}><h3>{title}</h3><ul>{(values as string[]).map(value => <li key={value}>{value}</li>)}</ul></motion.section>)}</div></section>
    <section className="education section" id="education"><motion.div {...reveal} className="section-label">04 / Education & engineering signal</motion.div><div className="education-grid"><motion.article {...reveal} className="education-card"><div className="education-icon"><BrainCircuit size={22}/></div><p className="date">Expected 2027</p><h2>Bowling Green State University</h2><p className="degree">Computer Science</p><p>I’m developing practical experience through production-minded projects: automated checks, API design, authentication and authorization boundaries, relational data modeling, and reproducible data workflows.</p></motion.article><motion.article {...reveal} className="leadership"><p className="date">Leadership</p><h3>Rocket League Team Captain</h3><p>Bowling Green State University Esports</p><p className="muted">Leading team communication and strategy under pressure informs how I approach collaboration, feedback, and product decisions.</p></motion.article></div></section>
    <section className="contact" id="contact"><div className="contact-ring" aria-hidden="true"/><motion.div {...reveal} className="contact-inner"><p className="section-label">05 / Contact</p><h2>Let’s talk about<br/><em>what you’re building.</em></h2><p>I’m looking for software engineering internships and early-career opportunities where I can contribute, learn quickly, and build useful products with a team.</p><a className="email-link" href={`mailto:${email}`}>{email} <ArrowUpRight/></a><div className="contact-actions"><a href={github} target="_blank" rel="noreferrer"><GitFork size={18}/> GitHub</a><a href={linkedin} target="_blank" rel="noreferrer"><Network size={18}/> LinkedIn</a><a href={resume} download><Download size={18}/> Download résumé</a><a href={`mailto:${email}`}><Mail size={18}/> Email</a></div></motion.div></section>
  </main><footer><a className="mark" href="#home" aria-label="Back to top">CS<span>.</span></a><span>Designed & built by Cade Schiano</span><span>© {new Date().getFullYear()}</span></footer></>
}
export default App
